/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OOPII.List6.Number1;


/**
 *
 * @author berse
 */
public class FrameCalc extends javax.swing.JFrame {

    /**
     * Creates new form FrameCalc
     */
    
    double result;
    double input_one;
    double input_two;
    String operation;
    
    public FrameCalc() {
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCalc = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jButtonClear = new javax.swing.JButton();
        jButtonBackSpace = new javax.swing.JButton();
        jButtonMult = new javax.swing.JButton();
        jButtonNumber7 = new javax.swing.JButton();
        jButtonNumber8 = new javax.swing.JButton();
        jButtonNumber9 = new javax.swing.JButton();
        jButtonDiv = new javax.swing.JButton();
        jButtonNumber4 = new javax.swing.JButton();
        jButtonNumber5 = new javax.swing.JButton();
        jButtonNumber6 = new javax.swing.JButton();
        jButtonEquals = new javax.swing.JButton();
        jButtonNumber1 = new javax.swing.JButton();
        jButtonNumber2 = new javax.swing.JButton();
        jButtonNumber3 = new javax.swing.JButton();
        jButtonNumber0 = new javax.swing.JButton();
        jButtonPoint = new javax.swing.JButton();
        jButtonPlus = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jTextFieldCalc.setEditable(false);
        jTextFieldCalc.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldCalc.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jButtonClear.setText("C");
        jButtonClear.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jButtonBackSpace.setText("<-");
        jButtonBackSpace.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonBackSpace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBackSpaceActionPerformed(evt);
            }
        });

        jButtonMult.setText("*");
        jButtonMult.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonMult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMultActionPerformed(evt);
            }
        });

        jButtonNumber7.setText("7");
        jButtonNumber7.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonNumber7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber7ActionPerformed(evt);
            }
        });

        jButtonNumber8.setText("8");
        jButtonNumber8.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonNumber8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber8ActionPerformed(evt);
            }
        });

        jButtonNumber9.setText("9");
        jButtonNumber9.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonNumber9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber9ActionPerformed(evt);
            }
        });

        jButtonDiv.setText("/");
        jButtonDiv.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonDiv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDivActionPerformed(evt);
            }
        });

        jButtonNumber4.setText("4");
        jButtonNumber4.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonNumber4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber4ActionPerformed(evt);
            }
        });

        jButtonNumber5.setText("5");
        jButtonNumber5.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonNumber5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber5ActionPerformed(evt);
            }
        });

        jButtonNumber6.setText("6");
        jButtonNumber6.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonNumber6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber6ActionPerformed(evt);
            }
        });

        jButtonEquals.setText("=");
        jButtonEquals.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonEquals.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEqualsActionPerformed(evt);
            }
        });

        jButtonNumber1.setText("1");
        jButtonNumber1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonNumber1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber1ActionPerformed(evt);
            }
        });

        jButtonNumber2.setText("2");
        jButtonNumber2.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonNumber2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber2ActionPerformed(evt);
            }
        });

        jButtonNumber3.setText("3");
        jButtonNumber3.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonNumber3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber3ActionPerformed(evt);
            }
        });

        jButtonNumber0.setText("0");
        jButtonNumber0.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonNumber0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNumber0ActionPerformed(evt);
            }
        });

        jButtonPoint.setText(".");
        jButtonPoint.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonPoint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPointActionPerformed(evt);
            }
        });

        jButtonPlus.setText("+");
        jButtonPlus.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });

        jButtonMinus.setText("-");
        jButtonMinus.setPreferredSize(new java.awt.Dimension(50, 50));
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonMult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonNumber9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jButtonNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonNumber0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jButtonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jButtonEquals, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBackSpace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonClear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonDiv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumber9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPlus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonMinus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonNumber0, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButtonEquals, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jTextFieldCalc))
                .addGap(10, 10, 10))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextFieldCalc, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNumber7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber7ActionPerformed
        // TODO add your handling code here:
        String input = jTextFieldCalc.getText() + jButtonNumber7.getText();
        jTextFieldCalc.setText(input);
    }//GEN-LAST:event_jButtonNumber7ActionPerformed

    private void jButtonNumber8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber8ActionPerformed
        // TODO add your handling code here:
        String input = jTextFieldCalc.getText() + jButtonNumber8.getText();
        jTextFieldCalc.setText(input);
    }//GEN-LAST:event_jButtonNumber8ActionPerformed

    private void jButtonNumber9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber9ActionPerformed
        // TODO add your handling code here:
        String input = jTextFieldCalc.getText() + jButtonNumber9.getText();
        jTextFieldCalc.setText(input);
    }//GEN-LAST:event_jButtonNumber9ActionPerformed

    private void jButtonNumber4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber4ActionPerformed
        // TODO add your handling code here:
        String input = jTextFieldCalc.getText() + jButtonNumber4.getText();
        jTextFieldCalc.setText(input);
    }//GEN-LAST:event_jButtonNumber4ActionPerformed

    private void jButtonNumber5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber5ActionPerformed
        // TODO add your handling code here:
        String input = jTextFieldCalc.getText() + jButtonNumber5.getText();
        jTextFieldCalc.setText(input);
    }//GEN-LAST:event_jButtonNumber5ActionPerformed

    private void jButtonNumber6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber6ActionPerformed
        // TODO add your handling code here:
        String input = jTextFieldCalc.getText() + jButtonNumber6.getText();
        jTextFieldCalc.setText(input);
    }//GEN-LAST:event_jButtonNumber6ActionPerformed

    private void jButtonNumber1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber1ActionPerformed
        // TODO add your handling code here:
        String input = jTextFieldCalc.getText() + jButtonNumber1.getText();
        jTextFieldCalc.setText(input);
    }//GEN-LAST:event_jButtonNumber1ActionPerformed

    private void jButtonNumber2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber2ActionPerformed
        // TODO add your handling code here:
        String input = jTextFieldCalc.getText() + jButtonNumber2.getText();
        jTextFieldCalc.setText(input);
    }//GEN-LAST:event_jButtonNumber2ActionPerformed

    private void jButtonNumber3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber3ActionPerformed
        // TODO add your handling code here:
        String input = jTextFieldCalc.getText() + jButtonNumber3.getText();
        jTextFieldCalc.setText(input);
    }//GEN-LAST:event_jButtonNumber3ActionPerformed

    private void jButtonNumber0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNumber0ActionPerformed
        // TODO add your handling code here:
        String input = jTextFieldCalc.getText() + jButtonNumber0.getText();
        jTextFieldCalc.setText(input);
    }//GEN-LAST:event_jButtonNumber0ActionPerformed

    private void jButtonPointActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPointActionPerformed
        // TODO add your handling code here:
        String input = jTextFieldCalc.getText();
        if(!input.contains(".")){
            input += jButtonPoint.getText();
            jTextFieldCalc.setText(input);
        }
        
        
    }//GEN-LAST:event_jButtonPointActionPerformed

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        jTextFieldCalc.setText(null);
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonMultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMultActionPerformed
        // TODO add your handling code here:
         input_one = Double.parseDouble(jTextFieldCalc.getText());
         jTextFieldCalc.setText("");
         operation = "*";
    }//GEN-LAST:event_jButtonMultActionPerformed

    private void jButtonDivActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDivActionPerformed
        // TODO add your handling code here:
        input_one = Double.parseDouble(jTextFieldCalc.getText());
         jTextFieldCalc.setText("");
         operation = "/";
    }//GEN-LAST:event_jButtonDivActionPerformed

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        // TODO add your handling code here:
        input_one = Double.parseDouble(jTextFieldCalc.getText());
         jTextFieldCalc.setText("");
         operation = "+";
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        // TODO add your handling code here:
        input_one = Double.parseDouble(jTextFieldCalc.getText());
         jTextFieldCalc.setText("");
         operation = "-";
    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void jButtonEqualsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEqualsActionPerformed
        // TODO add your handling code here:
        input_two = Double.parseDouble(jTextFieldCalc.getText());
        switch(operation){
            case "+":
                result = input_one + input_two;
                jTextFieldCalc.setText((String.format("%.2f", result)));
                break;
            case "-":
                result = input_one - input_two;
                jTextFieldCalc.setText((String.format("%.2f", result)));
                break;
            case "*":
                result = input_one * input_two;
                jTextFieldCalc.setText((String.format("%.2f", result)));
                break;
            case "/":
                result = input_one / input_two;
                jTextFieldCalc.setText((String.format("%.2f", result)));
                break;
            default:
                jTextFieldCalc.setText("NaN");
                break;
        }
    }//GEN-LAST:event_jButtonEqualsActionPerformed

    private void jButtonBackSpaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBackSpaceActionPerformed
        // TODO add your handling code here:
        String text = null;
        if(jTextFieldCalc.getText().length() > 0){
            StringBuilder builder = new StringBuilder(jTextFieldCalc.getText());
            builder.deleteCharAt(jTextFieldCalc.getText().length()-1);
            text = builder.toString();
            jTextFieldCalc.setText(text);
        }
    }//GEN-LAST:event_jButtonBackSpaceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCalc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCalc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBackSpace;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDiv;
    private javax.swing.JButton jButtonEquals;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonMult;
    private javax.swing.JButton jButtonNumber0;
    private javax.swing.JButton jButtonNumber1;
    private javax.swing.JButton jButtonNumber2;
    private javax.swing.JButton jButtonNumber3;
    private javax.swing.JButton jButtonNumber4;
    private javax.swing.JButton jButtonNumber5;
    private javax.swing.JButton jButtonNumber6;
    private javax.swing.JButton jButtonNumber7;
    private javax.swing.JButton jButtonNumber8;
    private javax.swing.JButton jButtonNumber9;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JButton jButtonPoint;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextFieldCalc;
    // End of variables declaration//GEN-END:variables
}
